import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>

      <Head>
        <title>Martin Kululanga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main>
        <div className="bg-purple-900 text-white min-h-screen flex items-center justify-center">
          <div className="bg-gray-800 p-8 rounded shadow-lg">
            <h1 className="text-4xl font-bold mb-4">Your Name</h1>
            <p className="text-gray-400 mb-4">Chemical Engineer & Software Developer</p>
            <p className="text-gray-400 mb-4">Graduated from MUST in 2019</p>
            <h2 className="text-2xl font-semibold mt-4">Achievements</h2>
            <ul className="list-disc pl-4">
              <li>Developed iMustSign - A Text to Signal Language system</li>
              <li>Created Learn Box - An interactive learning platform</li>
            </ul>
            <h2 className="text-2xl font-semibold mt-4">Professional Life</h2>
            <ul className="list-disc pl-4">
              <li>Owner of Learnbox, M2K Developments, and GMT3 Developers</li>
            </ul>
            <h2 className="text-2xl font-semibold mt-4">Hobbies</h2>
            <ul className="list-disc pl-4">
              <li>Writing stories</li>
              <li>Playing basketball</li>
              <li>Coding</li>
              <li>Drawing</li>
              <li>Teaching</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}
